name: bolter
version: 1.0.0
description: Simplest mutable state manager powered by dart streams and it's extensions
homepage: https://github.com/Renesanse/bolter

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
