name: bolter
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
